USE [master]
GO

/****** Object:  Database [YSD_DB]    Script Date: 12/13/2018 12:48:44 PM ******/
CREATE DATABASE [YSD_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'YSD_DB', FILENAME = N'D:\PLESKMSSQL\Data\YSD_DB.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'YSD_DB_log', FILENAME = N'D:\PLESKMSSQL\Data\YSD_DB_log.ldf' , SIZE = 5696KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [YSD_DB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [YSD_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [YSD_DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [YSD_DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [YSD_DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [YSD_DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [YSD_DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [YSD_DB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [YSD_DB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [YSD_DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [YSD_DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [YSD_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [YSD_DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [YSD_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [YSD_DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [YSD_DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [YSD_DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [YSD_DB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [YSD_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [YSD_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [YSD_DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [YSD_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [YSD_DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [YSD_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [YSD_DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [YSD_DB] SET RECOVERY FULL 
GO

ALTER DATABASE [YSD_DB] SET  MULTI_USER 
GO

ALTER DATABASE [YSD_DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [YSD_DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [YSD_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [YSD_DB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [YSD_DB] SET  READ_WRITE 
GO

